apiVersion: v1
kind: Service
metadata:
  name: {{ include "opencve.fullname" . }}
  labels:
    {{- include "opencve.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }} 
      protocol: TCP
  selector:
    app: webserver
    {{- include "opencve.selectorLabels" . | nindent 4 }}
